const express = require('express');
const {MongoClient} = require('mongodb');
const debug = require('debug')('app:mongo');
const adminRouter = express.Router();

const recipes = [{"name": "basil pesto pasta","prep_time": "15 mins", "cook_time": "20 mins", "ingredients": "basil, pine nuts, minced garlic, olive oil, salt & pepper, parmesan cheese", "description": "A beautiful pasta and a fresh pesto makes for an amazing dinner or lunch!", "directions": "make pasta and sauce", "creator": "admin", "public": true, "likes": 0},
                {"name": "Poached Egg over Spinach", "prep_time": "5 min", "cook_time": "10 min", "ingredients": "1 bunch spinach, 1 omega-rich egg, 1 TBS sunflower seeds, 1 TBS Mediterranean Dressing", "description": "Combining eggs with a green leafy vegetables makes for a great tasty and nutritious breakfast. And it takes little time to prepare!", "directions": "1. Bring lightly salted water to a rapid boil in a large pot.   2. Cut stems off spinach leaves and clean well. This can be done easily by leaving spinach bundled and cutting off stems all at once. Rinse spinach leaves very well as they often contain a lot of soil. 3. Cook spinach in boiling water for 1 minute. 4. Drain and press out excess water and toss with Mediterranean Dressing. 5.Top with poached and sunflower seeds.", "creator": "admin", "creator": "admin", "public": true, "likes": 0},
                {"name": "Crispy Turkey Salad", "prep_time": "10 min", "cook_time": "5 min", "ingredients": "4 cups mixed salad greens, 1/2 medium tomato, sliced, 3 oz sliced turkey breast, cut into 1/2-inch strips, 2 oz crimini mushrooms, sliced, 1 TBS blue cheese dressing", "description": "Add this nutrient-rich, meal-in-one salad to your Healthiest Way of Eating. Since salads are only limited by your imagination add any of your favorite vegetables to this recipe.", "directions": "Top salad greens with rest of ingredients and top with blue cheese dressing (or your favorite vinaigrette).Serves 1", "creator": "admin", "creator": "admin", "public": true, "likes": 0},
                {"name": "Spicy Asian Shrimp", "prep_time": "15 min", "cook_time": "20 min", "ingredients": "1/2 lb medium-sized shrimp, peeled and deveined, 2 TBS + 1 TBS fresh lemon juice, Sea salt and pepper to taste, 3 TBS low-sodium chicken or vegetable broth, 2 medium garlic cloves, 1/8 tsp red pepper flakes, 1/4 cup orange juice, 1 TBS minced fresh ginger, 1 TBS extra virgin olive oil", "description": "Spice up your meal and spice up your health with this Asian shrimp recipe. This nutrient-rich dish contains over 40% of the daily value for selenium, vitamin C, protein, and vitamin D.", "directions": "1. Chop garlic and let sit for 5 minutes to enhance its health-promoting properties. 2. Peel and devein shrimp. 3. Rub shrimp with 2 TBS lemon juice, salt and pepper. 4. Heat 3 TBS broth over medium-low heat in a stainless steel skillet. 5. When broth begins to steam, add shrimp, red pepper flakes, orange juice, and ginger and saute. Stir frequently. After 2 minutes, turn the shrimp over and add garlic. Saute until shrimp are pink and opaque throughout (approximately 3 minutes). Shrimp cook quickly, so watch your cooking time. They become tough if overcooked. 5. Dress with the extra virgin olive oil and the remaining 1 TBS lemon juice.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Salmon with Mustard and Ginger", "prep_time": "15 min", "cook_time": "30 min", "ingredients": "8 oz salmon fillets, 2 tsp + 1 TBS lemon juice, 1 TBS extra virgin olive oil, 1 clove garlic, pressed, 1 tsp yellow or Dijon mustard, 1/2 tsp soy sauce, 2 TBS cilantro, 2 TBS grated ginger, sea salt and pepper to taste", "description": "Try this easy-to-prepare recipe not only for great taste but to add an extra boost of those hard-to-find omega-3 fatty acids to your Healthiest Way of Eating. Enjoy!", "directions": "1. To Quick Broil salmon, preheat broiler and place an all stainless steel skillet (be sure the handle is also stainless steel) or cast iron pan under the heat for about 10 minutes to get it very hot. The pan should be 5 to 7 inches from the heat source. 2. Rub salmon with 2 tsp fresh lemon juice, salt and pepper. (You can Quick Broil with the skin on; it just takes a minute or two longer. The skin will peel right off after cooking.) 3. Using a hot pad, pull pan away from heat and place salmon on hot pan, skin side down. Return to broiler. Keep in mind that it is cooking rapidly on both sides so it will be done very quickly, usually in 7 minutes depending on thickness. Test with a fork for doneness. It will flake easily when it is cooked. Salmon is best when it is still pink inside. 4. Top salmon 1 TBS lemon juice and the remaining ingredients.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Curried Chicken Over Spinach", "prep_time": "15 min", "cook_time": "45 min", "ingredients": "3 boneless chicken breasts cut into bite sized pieces (6oz each), 1 1/2 cup chicken stock, 3 cloves garlic sliced, 1 TBS fresh ginger chopped, or 1/2 tsp dried, 1/2 tsp turmeric, 1 tsp curry powder, 1 medium sized onion cut in half and sliced, 1 medium sized red bell pepper julienne about 1 inch long, 1/2 cup coconut milk, make sure it is mixed well before using, 4 bunches fresh spinach", "description": "This is a great tasting dish that requires little work. The curry coconut complements the flavor of spinach and you can easily include more vegetables. Just increase the amount of sauce slightly and add along with the bell peppers.", "directions": "1. Bring water to a boil for spinach. While water is coming to a boil, cut chicken into bite sized pieces.Healthy Sautued Onion in a medium saute pan over medium low heat for about 5 minutes stirring frequently. Add garlic and fresh ginger and continue to saute for another minute. Add turmeric, and curry and mix well. Add stock, chicken, and coconut milk. Simmer for 5 minutes and add bell peppers and other vegetables you desire. Cook until chicken is done, about another 5 minutes. 2. While chicken is cooking, cut ends off the bunch of spinach all at once. Don't bother trying to do it one stem at a time. It will take you too long and it is not necessary. Rinse spinach well and drop into boiling water for just 1 minute. Strain and press dry. Season with salt and pepper. 3. Place spinach on plates and top with chicken mixture.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Roast Leg of Lamb", "prep_time": "15 min", "cook_time": "60 min", "ingredients": "butt half of boneless leg of lamb, 8 cloves of garlic pressed, 3 TBS chopped rosemary, 1/4 cup fresh lemon juice, 2 tsp salt, 1 tsp fresh ground pepper, 3 carrots, peeled and sliced, 2 onions, quartered, 11/2 cups chopped celery", "description": "Roasted Leg of lamb with veggies", "directions": "1. Cut off excess fat from leg of lamb. Lay leg of lamb out flat in glass baking dish. Press garlic and chop rosemary. Rub leg with both making sure you get it into the crevices. Pour fresh lemon juice over lamb and sprinkle with salt. Cover and refrigerate overnight. 2. Preheat the oven to 425F (218C). Cut vegetables and place around lamb in baking dish. Sprinkle with pepper. Roast lamb and vegetables for about 15 minutes, then turn the heat down to 350F (177C). 3. After about 20 minutes, check the internal temperature of the lamb with an instant reading meat thermometer. Continue to check in thickest part of leg every 5 minutes until internal temperature reaches 130F (55C) for medium rare. Let it rest for a few minutes before carving. Serve with vegetables and pan juices. 4. If vegetables are not yet tender, pour them into a pan with juice and simmer, covered over medium heat while lamb rests.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Spicy Vegetable Tart", "prep_time": "35 min", "cook_time": "25 min", "ingredients": "4 cups chopped Swiss chard, 1 TBS chicken or vegetable broth, 2 cups sliced crimini mushroom, 1 small onion, minced, 3 medium cloves garlic, minced, 1-1/2 tsp dried Italian herbs, pinch of red chili flakes, 1 small tomato, chopped, seeds removes, 5 oz silken tofu, 5 egg whites, 1/8 tsp turmeric", "description": "Enjoy the wealth of nutrients in this unique tart, which is a wonderful treat when you have a little extra time to prepare your meal.", "directions": "1. Preheat oven to 350F (175C). 2. Soak flax seeds in 1/4 cup water for 10 minutes. 3. While flax seeds are soaking, grind rest of crust ingredients in food processor. It should be finely ground when done. Add flax seeds and soaking water to crust ingredients and continue to process for another 30 seconds. Press evenly into a 9-inch tart pan making sure you come up to the top edge so crust isn't too thick on the bottom. Bake crust in oven for 15 minutes. 4. While crust is baking, chop onion and garlic and let sit for 5 minutes to bring out their hidden health benefits. 5. Bring lightly salted water to a boil. Cook chopped chard for about 3 minutes in boiling water and drain. This will reduce oxalic acid from chard and make it sweeter. 6. Heat 1 TBS broth in a medium stainless steel skillet. Healthy Saute minced onion, garlic, and mushrooms in broth for 5 minutes stirring frequently. 7. Add herbs, tomatoes, salt and pepper, and saute for 2 minutes. Press out excess water from chard and add to rest of vegetables. 8. Remove from heat and spread evenly over crust in tart shell. 9. Blend egg whites, silken tofu, turmeric, and a little salt and pepper in blender. Pour evenly over vegetables and bake for another 25 minutes. 10. With the tip of a knife loosen around edges of crust and remove ring. Cut into wedges and serve.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Roasted Beets", "prep_time": "7 min", "cook_time": "55 min", "ingredients": "6 small whole beets, 2 small yellow onions, 2 TBS balsamic vinegar, 2 TBS extra virgin olive oil, 2 medium cloves garlic, pressed, 2 TBS coarsely chopped walnuts, salt and cracked black pepper to taste, 1 TBS chopped fresh parsley", "description": "Roasting is one of the best way to cook beets, as it brings out their wonderful buttery flavor. This easy-to-prepare, healthy recipe does just that.", "directions": "1. Preheat oven to 400F/200C. Wash beets well and place in a baking dish just big enough to hold beets, and onions without crowding them. If onions are small, just leave whole with skin on. If they are medium sized, cut in half leaving the skin on. 2. Cover and roast for about 55 minutes, stirring occasionally, until you can slide tip of sharp knife into the center of the beets fairly easily. Remove from oven. 3. When beets and onions have cooled enough to handle, peel and cut into bite-sized pieces. Toss with vinegar, olive, oil, garlic, and chopped walnuts. Add salt and pepper to taste. 4. Top with chopped parsley.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Chicken and Kale", "prep_time": "5 mins", "cook_time": "15 mins", "ingredients": "1 cup sliced leeks, 4 cups chopped kale, 1 TBS + 1/4 cup chicken or vegetable broth, 3 medium cloves garlic, pressed, 1 tsp fresh lemon juice, 1 TBS extra virgin olive oil", "description": "This recipe is a great tasting way of receiving the many health benefits of the super food kale. The leeks are a delicious complement. This dish can be made very easily, so you can have it often. Adding the oil at the end gives it a rich taste without heating it, making this even healthier than most sauted greens.", "directions": "1. Heat 1 TBS broth in a 10-12 inch stainless steel skillet.Healthy Sliced leeks in broth over medium-low heat for about 5 minutes, stirring frequently. Add kale and 1/4 cup broth. 2. Cover and simmer on low heat for about 7-8 minutes, stirring occasionally. 3. Toss with pressed garlic, lemon juice, soy sauce, olive oil, salt, and pepper.", "creator": "admin", "public": true, "likes": 0},
                {"name": "Apple Treats", "prep_time": "5 min", "cook_time": "0 min", "ingredients": "1 apple, slice 1/2-inch thick, unpeeled, 3 TBS almond butter, cinnamon to taste, 1/4 cup granola", "description": "Fresh apples are a great snack any time of day.", "directions": "1. Spread one side of slliced apple with almond butter and spinkle with cinnamon. 2. Dip the apple slices into granola to cover the almond butter.", "likes": 0}]

function router() {
    adminRouter.route('/')
    .get((req, res) => {
        const url = 'mongodb://localhost:27017';
        const dbName = 'Paughers';

        (async function mongo(){
            let client;
            try {
                client = await MongoClient.connect(url);
                debug('Connected correctly to server');

                const db = client.db(dbName);

                const col = db.collection('recipes');

                col.deleteMany({});
                const response = await col.insertMany(recipes);
                res.redirect('/');
            } catch (err) {
                debug(err.stack);
            }

            client.close();
        }())
    });
    return adminRouter;
}

module.exports = router;